spring.application.name=theMediaVault

# DATABASE CONFIG
spring.datasource.url=
spring.datasource.driver-class-name=
spring.datasource.username=
spring.datasource.password=

# JPA CONFIG
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# SECURITY CONFIG
spring.security.user.name=
spring.security.user.password=