spring.application.name=theMediaVault
server.port=9090

# max upload file size
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=2GB

# DATABASE CONFIG
spring.datasource.url=
spring.datasource.driver-class-name=
spring.datasource.username=
spring.datasource.password=

# JPA CONFIG
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# SECURITY CONFIG
spring.security.user.name=
spring.security.user.password=
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR

# JWT
jwt.secret=

# milisecond
jwt.token.expiration=

# minio
minio.url=
minio.accessKey=
minio.secretKey=
minio.bucket=